apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
   metadata:
      labels:
        app: jenkins
   spec:
    containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        #image: thai2305/jenkins-server
        ports:
         - containerPort: 8080
    #     volumeMounts:
    #       - name: persistent-storage
    #         mountPath: /var/jenkins_home
    # volumes:
    #   - name: persistent-storage
    #     persistentVolumeClaim:
    #       claimName: ebs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector: 
    app: jenkins
  type: LoadBalancer  
  ports:
    - port: 8080
      targetPort: 8080
